### ISSUE TITLE
IdxReader improvement

### ISSUE THREAD

**Issue by Evegen55** [klevis/DigitRecognizer#4]
this class is responsible for read binary files, create a composed object and then populates ArrayList with given amount of data. There is a few places to inprove - for instance, move the part of code which reads only couple fields into JUnit tests (magic numbers) - and add into README an appropriate note to run tests before buid. The try-with-resources, then move 784 integer into public constant which can be used from any other class.

**Comment by klevis** [comment]
Contribution are welcomed :)

**Comment by klevis** [comment]
Contribution are welcomed :)

**Comment by Evegen55** [comment]
it's done, please verify changes - but I made commits to my master branch - it's my fault )

**Comment by klevis** [comment]
Thank you , nice code.
